[package]
name = "cyberex"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = """
Utilities Library
"""
authors = ["Su", "469446490@qq.com"]
repository = "https://github.com/swq123459/cyberex.git"
keywords = ["utilities"]

exclude = [
    ".devcontainer/**",
    "videos/*",
]

[dependencies]
